[package]
name = "sjmb_matrix"
version = "1.1.0"
edition = "2021"
resolver = "2"
authors = ["Sami J. Mäkinen <sjm@iki.fi>"]
description = "My Matrix bot"
repository = "https://github.com/sjm42/sjmb-matrix"
readme = "README.md"
keywords = ["matrix", "bot"]
license = "MIT OR Apache-2.0"


[dependencies]
anyhow = "1.0"
chrono = "0.4"
chrono-tz = "0.8"
env_logger = "0.10"
futures = "0.3"
http = "0.2"
log = "0.4"
matrix-sdk = { git = "https://github.com/matrix-org/matrix-rust-sdk.git", default-features = false, features = [
    "e2e-encryption",
    "anyhow",
    "rustls-tls",
    "sqlite",
] }
once_cell = "1.18"
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = { version = "3.1", features = ["full"] }
sqlx = { version = "0.7", features = [
    "macros",
    "migrate",
    "runtime-tokio-rustls",
    "sqlite",
] }
structopt = "0.3"
tokio = { version = "1.33", features = ["full"] }


[build-dependencies]
build-data = "0.1"


[profile.release]
lto = true
opt-level = 3

# EOF
